version: 2
jobs:
  build:
    machine:
      node:
        version: 8.9.4
    working_directory: ~/repo
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: npm install
      - run: npm test
